version: '2'
services:
  web:
    build: .
    image: laravel-build
    ports:
      - '80:80'
      - '5432:5432'
    volumes:
      - './whost:/etc/apache2/from-host'
      - './project:/var/www/html'
